export const glasses = [
  {
    id: 1,
    name: "Astral Green Titanium",
    url: "astral-green-titanium",
    img: "/glasses1.webp",
    price: "4 440 000",
    type: "Indoor",
    sex: "Unisex",
    description: "Тип: Для помещений\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 2,
    name: "Eclipse Blue Zebra",
    url: "eclipse-blue-zebra",
    img: "/glasses2.webp",
    price: "4 340 000",
    type: "Outdoor",
    sex: "Woman",
    description: "Тип: Для улицы\nЖенские очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 3,
    name: "Lunar Gold",
    url: "lunar-gold-indoor",
    img: "/glasses3.webp",
    price: "5 000 000",
    type: "Indoor",
    sex: "Woman",
    description: "Тип: Для помещений\nЖенские очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 4,
    name: "Galactic Rose Gold Titanium",
    url: "galactic-rose-gold-titanium",
    img: "/glasses4.webp",
    price: "4 340 000",
    type: "Indoor",
    sex: "Woman",
    description: "Тип: Для помещений\nЖенские очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 5,
    name: "Nebula Red Titanium",
    url: "nebula-red-titanium-outdoor",
    img: "/glasses5.webp",
    price: "5 000 000",
    type: "Outdoor",
    sex: "Unisex",
    description: "Тип: Для улицы\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 6,
    name: "Nebula Red Titanium",
    url: "nebula-red-titanium-indoor",
    img: "/glasses6.webp",
    price: "5 450 000",
    type: "Indoor",
    sex: "Unisex",
    description: "Тип: Для помещений\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 7,
    name: "Lunar Gold",
    url: "lunar-gold-outdoor",
    img: "/glasses7.webp",
    price: "5 570 000",
    type: "Outdoor",
    sex: "Woman",
    description: "Тип: Для улицы\nЖенские очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 8,
    name: "Stellar Havana",
    url: "stellar-havana",
    img: "/glasses8.webp",
    price: "5 450 000",
    type: "Outdoor",
    sex: "Woman",
    description: "Тип: Для улицы\nЖенские очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 9,
    name: "Stardust Amber",
    url: "stardust-amber",
    img: "/glasses9.webp",
    price: "5 570 000",
    type: "Outdoor",
    sex: "Unisex",
    description: "Тип: Для улицы\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 10,
    name: "Halo Black Clip-on",
    url: "halo-black-clip-on-1",
    img: "/glasses10.webp",
    price: "4 340 000",
    type: "Outdoor and Indoor",
    sex: "Unisex",
    description: "Тип: Для улицы и помещений\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 11,
    name: "Halo Black Clip-on",
    url: "halo-black-clip-on-outdoor",
    img: "/glasses11.webp",
    price: "4 890 000",
    type: "Outdoor",
    sex: "Unisex",
    description: "Тип: Для улицы\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 12,
    name: "Zero G Black Titanium",
    url: "zero-g-black-titanium-indoor",
    img: "/glasses12.webp",
    price: "5 340 000",
    type: "Indoor",
    sex: "Unisex",
    description: "Тип: Для помещений\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 13,
    name: "Zero G Black Titanium",
    url: "zero-g-black-titanium-outdoor",
    img: "/glasses13.webp",
    price: "5 890 000",
    type: "Outdoor",
    sex: "Unisex",
    description: "Тип: Для улицы\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
  {
    id: 14,
    name: "Nimbus Gold Titanium",
    url: "nimbus-gold-titanium",
    img: "/glasses14.webp",
    price: "5 000 000",
    type: "Indoor",
    sex: "Unisex",
    description: "Тип: Для помещений\nУнисекс очки",
    category: "glasses",
    category_name: "Очки",
  },
];
